// ⚠️ PLACEHOLDER — replace by running `flutterfire configure` in this project.
//
// This file is normally generated by the FlutterFire CLI and contains your
// Firebase project's *public* client configuration for each platform. The
// values below are dummies so the project compiles before you wire up Firebase.
// Running `flutterfire configure` will overwrite this file with real values.
//
// See README.md → "Firebase setup" for the full step-by-step.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.\n'
          'Run `flutterfire configure` to regenerate firebase_options.dart.',
        );
    }
  }

  // The values below are placeholders. Replace via `flutterfire configure`.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmXSpv7Vys00SwmPcitwlA0vNRrofnQvo',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'gold-invest-c79a2',
    storageBucket: 'gold-invest-c79a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'replace-me',
    storageBucket: 'replace-me.appspot.com',
    iosBundleId: 'com.example.goldInvest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'replace-me',
    authDomain: 'replace-me.firebaseapp.com',
    storageBucket: 'replace-me.appspot.com',
  );
}
